### ISSUE TITLE
sprinkle.only option does not seem to work

### ISSUE THREAD

**Issue by priithaamer** [jimmycuadra/vagrant-sprinkle#1]
Doing this:

``` ruby
config.vm.provision(:sprinkle) do |sprinkle|
  sprinkle.only = 'my_role'
end
```

Raises an error:

```
~/.vagrant.d/gems/gems/sprinkle-0.7.6.2/bin/sprinkle:62:in `block in <top (required)>': invalid option: --only edicy_db_backup (OptionParser::InvalidOption)
```

I managed to get it working by changing the [line 19 in provisioner.rb](https://github.com/jimmycuadra/vagrant-sprinkle/blob/master/lib/vagrant-sprinkle/provisioner.rb#L19) like this:

``` ruby
options << "--only=#{config.only}" if config.only
```

If you confirm this would be an acceptable change i'll do a PR.

**Comment by jimmycuadra** [comment]
Yes, I'd gladly accept that patch. Thank you!
