### ISSUE TITLE
Dependency on vagrant in Gemfile

### ISSUE THREAD

**Issue by davetapley** [jimmycuadra/vagrant-sprinkle#4]
The [Gemfile](https://github.com/velocity-labs/vagrant-sprinkle/blob/cbf3bb1b651fc4eca05b781ebf0126fb2c904250/Gemfile) has `gem 'vagrant'`, but the [plugin  packaging docs](https://docs.vagrantup.com/v2/plugins/packaging.html) say:

> Do not depend on Vagrant for your gem. Vagrant is no longer distributed as a gem, and you can assume that it will always be available when your plugin is installed.

Is there any reason to keep the dependency?

**Comment by jimmycuadra** [comment]
You are correct. That is a vestige from an older style of Vagrant plugin packaging. Instead, it should be done like [this](https://github.com/jimmycuadra/vagrant-librarian-chef/blob/088cb65af37233969cc3f2d1db2ed9b7806132c2/lib/vagrant-librarian-chef/plugin.rb#L1). I will update it and release a new version later this evening!

**Comment by jimmycuadra** [comment]
Reading this again, I realize you're talking about the Gemfile and not the gemspec. You're supposed have the Git version of Vagrant referenced in your Gemfile – that's how you load it while developing the plugin. The quote you included from the Vagrant documentation is referring to having a dependency on the Vagrant gem in the plugin's gemspec, which will cause the plugin to have a hard dependency on the old, deprecated Vagrant gem.
